language: cpp

os: linux
dist: bionic

jobs:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang
    - os: osx
    - os: windows

script:
  - echo $TRAVIS_BUILD_DIR
  - cd "$TRAVIS_BUILD_DIR"
  - git clone --branch v2.11.1 --depth 1 https://github.com/catchorg/Catch2.git
  - cmake -Bcatch2-build -HCatch2 -DBUILD_TESTING=OFF -DCATCH_INSTALL_DOCS=OFF
  - DESTDIR=inst cmake --build catch2-build/ --target install
  - cmake -Bthe-build -H. "-DCatch2_DIR=$TRAVIS_BUILD_DIR/catch2-build/inst" -DSEARCH_CATCH2=yes
  - cmake --build the-build/
  - cd the-build && ctest
